

export const SITE_CONFIG = {
  name: "ABS Corporation™",
  fullName: "Avatar Branding System Corporation",
  tagline: "L'Ingénierie de votre Autorité Numérique",
  description: "Le premier cabinet africain de Digital Human Branding. Transformez votre expertise en actif numérique immortel grâce à l'IA.",
  url: "https://abscorporation.com",
  email: "contact@abscorporation.com",
  whatsapp: "+22892813232",
  whatsappMessage: "Bonjour ABS Corporation, je souhaite en savoir plus sur vos services de Digital Human Branding.",
  address: "Lomé, Togo",
  socials: {
    linkedin: "#",
    twitter: "#",
    instagram: "#",
    youtube: "#",
    facebook: "#",
  },
};



export const NAV_LINKS = [
  { label: "Accueil", href: "/" },
  { label: "Services", href: "/services" },
  { label: "ABS Académie", href: "/academie" },
  // { label: "Portfolio", href: "/portfolio" },
  { label: "À Propos", href: "/about" },
  { label: "Tarifs", href: "/tarifs" },
  // { label: "Blog", href: "/blog" },
  { label: "Contact", href: "/contact" },
];

export const SERVICES = [
  {
    id: "avatar-system",
    title: "L'Avatar System™",
    subtitle: "Votre clone numérique vidéo/voix pour une présence 24/7",
    description: "Notre technologie propriétaire capture votre essence — voix, expressions faciales, gestuelle — pour créer un avatar numérique ultra-réaliste qui vous représente 24h/24, 7j/7. Votre clone numérique produit du contenu, forme vos équipes et engage votre audience pendant que vous vous concentrez sur la stratégie.",
    icon: "User",
    features: ["Captation vidéo 4K professionnelle", "Clonage vocal ultra-réaliste", "Avatar vidéo personnalisé", "Livraison en 72H", "Fichiers sources sécurisés"],
    delay: "72H",
    hasAvatar: true,
    hasVoice: true,
    hasStrategy: false,
    isMultilingual: false,
    hasFollowUp: false,
  },
  {
    id: "branding-ia-360",
    title: "Branding IA 360°",
    subtitle: "Refonte complète de votre identité visuelle et textuelle par l'IA",
    description: "Un audit complet de votre marque suivi d'une refonte intégrale assistée par l'intelligence artificielle. Logo, charte graphique, templates réseaux sociaux, pitch deck, bio officielle — nous construisons une identité cohérente et premium qui vous positionne comme un leader.",
    icon: "Palette",
    features: ["Audit de marque complet", "Refonte identité visuelle", "Templates réseaux sociaux", "Pitch deck professionnel", "Bio officielle optimisée"],
    delay: "2 semaines",
    hasAvatar: false,
    hasVoice: false,
    hasStrategy: true,
    isMultilingual: false,
    hasFollowUp: false,
  },
  {
    id: "ambassadeur-immortel",
    title: "Ambassadeur Immortel™",
    subtitle: "Pack premium pour créer, rendre célèbre et immortaliser votre avatar",
    description: "Notre offre phare combine l'Avatar System™, le Branding IA 360° et une stratégie de diffusion complète avec suivi sur 3 mois. Nous créons votre jumeau numérique, construisons votre image de marque et déployons votre présence sur toutes les plateformes.",
    icon: "Crown",
    features: ["Avatar System™ complet", "Branding IA 360°", "Stratégie de diffusion", "Suivi 3 mois", "Account Manager dédié", "Langues illimitées"],
    delay: "4 semaines",
    hasAvatar: true,
    hasVoice: true,
    hasStrategy: true,
    isMultilingual: true,
    hasFollowUp: true,
  },
  {
    id: "clonage-vocal",
    title: "Clonage Vocal Multilingue",
    subtitle: "Votre voix, traduite en toutes les langues locales et internationales",
    description: "Grâce à notre technologie de clonage vocal, votre voix est reproduite avec une fidélité exceptionnelle dans plus de 10 langues, incluant les langues locales africaines. Idéal pour les formations, publicités, podcasts et communications multilingues.",
    icon: "Mic",
    features: ["Clonage vocal haute fidélité", "+10 langues disponibles", "Langues locales africaines", "Accents préservés", "Livraison en 48H"],
    delay: "48H",
    hasAvatar: false,
    hasVoice: true,
    hasStrategy: false,
    isMultilingual: true,
    hasFollowUp: false,
  },
];


export const WORKFLOW_STEPS = [
  { step: 1, title: "Extraction ADN Oratoire", description: "Séance d'immersion totale : 6 min de données visuelles 4K pour la cartographie faciale + 2h de captation audio HD. Chaque nuance et intonation encodée." },
  { step: 2, title: "Forge Identitaire", description: "Entraînement de vos réseaux neuronaux dédiés. Votre jumeau est forgé et crypté au sein de l'Identity Vault™, exclusivité et sécurité totales." },
  { step: 3, title: "Ingénierie Narrative", description: "Nos architectes de contenu conçoivent vos scripts d'autorité, alignant vision stratégique et algorithmes de rétention performants." },
  { step: 4, title: "Matérialisation", description: "Activation de votre double via nos infrastructures propriétaires. Votre message prend vie avec fluidité organique et puissance inégalée." },
  { step: 5, title: "Raffinement", description: "Étalonnage chromatique cinématographique, typographies premium et synchronisation labiale parfaite." },
  { step: 6, title: "Certification Éthique", description: "Contrôle de conformité rigoureux et application du watermark « Verified by ABS Corp™ », attestant l'authenticité institutionnelle." },
  { step: 7, title: "Déploiement", description: "Livraison via canal crypté ou injection directe dans votre écosystème de diffusion pour une omniprésence immédiate." },
];

export const TEAM_MEMBERS = [
  {
    name: "Raphael Sossoe",
    role: "CEO & Fondateur",
    bio: "Visionnaire du Digital Human Branding en Afrique, Raphael a fondé ABS Corporation avec la conviction que chaque leader mérite une présence numérique immortelle.",
    avatar: "/members/PORTRAIT CEO.jpg",
  },
  {
    name: "Aimé Kook",
    role: "Chief AI Officer",
    bio: "Expert en intelligence artificielle et en technologies de synthèse vocale et vidéo, Aimé dirige l'innovation technologique d'ABS Corporation.",
    avatar: "/members/PORTAIT AIME.jpeg",
  },
  {
    name: "Frank KOSSI",
    role: "Product Manager",
    bio: "Architecte des solutions technologiques, Frank supervise la création et l'optimisation de nos produits pour garantir une performance et une innovation constantes.",
    avatar: "/members/PORTRAIT FRANK.jpg",
  },
  {
    name: "Amina M'DRAMA",
    role: "Brand manager",
    bio: "Spécialiste en branding et marketing digital, Amina est la garante de l'identité et de la réputation des leaders que nous accompagnons.",
    avatar: "/members/PORTRAT AMINA.jpg",
  },
];

export const FAQ_HOME = [
  {
    question: "Qu'est-ce qu'un avatar IA professionnel ?",
    answer: "Un avatar IA professionnel est une reproduction numérique ultra-réaliste de vous-même — voix, expressions faciales et gestuelle — créée grâce à l'intelligence artificielle. Il peut produire du contenu vidéo, animer des formations et représenter votre marque 24h/24 dans plusieurs langues.",
  },
  {
    question: "Est-ce que mon image sera protégée ?",
    answer: "Absolument. Votre identité numérique est stockée dans notre Identité Vault sécurisé. Nous appliquons notre Charte de Souveraineté Numérique qui garantit que vous restez propriétaire exclusif de votre avatar. Chaque vidéo produite porte le watermark « Verified by ABS Corp™ » pour l'authenticité.",
  },
  {
    question: "Combien de temps faut-il pour créer mon avatar ?",
    answer: "Le processus complet prend 72 heures après votre session de captation. La captation elle-même ne nécessite que 2 minutes de vidéo 4K et 5 minutes d'audio. Notre workflow optimisé en 7 étapes garantit une livraison rapide sans compromettre la qualité.",
  },
  {
    question: "L'avatar sera-t-il reconnu comme IA ou comme moi ?",
    answer: "Nos avatars sont conçus pour être ultra-réalistes tout en respectant la transparence éthique. Le watermark « Verified by ABS Corp™ » identifie clairement le contenu comme généré par IA, conformément à notre engagement éthique. Visuellement et vocalement, la ressemblance est saisissante.",
  },
  {
    question: "Dans quelles langues peut parler mon avatar ?",
    answer: "Votre avatar peut s'exprimer dans plus de 10 langues, incluant le français, l'anglais, l'espagnol, l'arabe, et plusieurs langues locales africaines (éwé, mina, fon, yoruba, etc.). Le clonage vocal préserve votre timbre et votre accent naturel dans chaque langue.",
  },
];

export const PRICING_PLANS = {
  empreinte: {
    name: "PACK EMPREINTE (Clone Social)",
    subtitle: "L'Actif Identitaire Souverain",
    description: "Le socle de votre immortalité numérique.",
    price: 500000,
    promoPrice: 150000,
    currency: "FCFA",
    delay: "72 heures après captation",
    sections: [
      {
        title: "Ingénierie de Captation & ADN Visuel",
        items: [
          "Protocole \"Studio Premier\" : Session de captation professionnelle en 4K Cinématique pour encoder chaque micro-expression et posture d'autorité.",
          "Modélisation Faciale IA Haute Fidélité : Entraînement profond de votre modèle pour une fluidité de mouvement indiscernable de la réalité.",
        ],
      },
      {
        title: "Architecture Vocale & Signature Oratoire",
        items: [
          "Clonage Vocal Souverain : Restitution de votre timbre de voix avec une précision chirurgicale.",
          "Préservation des Nuances : Intégration de vos accents locaux et tics de langage pour une authenticité absolue.",
        ],
      },
      {
        title: "Livrables Stratégiques (Le Pack de Lancement)",
        items: [
          "Le Manifeste de l'Omniprésence : 1 vidéo institutionnelle de 2 minutes, scénarisée pour installer votre autorité dès le premier jour.",
          "Votre \"Coffre-Fort\" Numérique : Livraison des fichiers sources sécurisés et cryptés, garantissant que vous restez l'unique propriétaire de votre double numérique.",
        ],
      },
      {
        title: "Avantages Exclusifs ABS Corp",
        items: [
          "Standard de Sécurité : Votre avatar est protégé contre les détournements (Anti-Deepfake protocol).",
          "Souveraineté Totale : Aucun abonnement tiers. Votre actif vous appartient à vie.",
        ],
      },
    ],
    includes: [
      "Captation professionnelle 4K Cinématique",
      "Modélisation Faciale IA Haute Fidélité",
      "Clonage Vocal Souverain",
      "Préservation des accents locaux",
      "1 vidéo manifeste de 2 minutes",
      "Fichiers sources sécurisés et cryptés",
      "Anti-Deepfake protocol",
      "Souveraineté totale à vie",
    ],
  },
  subscriptions: [
    {
      id: "bronze",
      name: "BRONZE",
      subtitle: "Visibilité",
      price: 300000,
      promoPrice: 200000,
      currency: "FCFA/mois",
      features: {
        videos: "8 vidéos (2/semaine)",
        scripts: true,
        languages: "1 langue",
        comments: false,
        multiplatform: false,
        ghostwriting: false,
        accountManager: false,
        monthlyReport: false,
        whatsappVIP: false,
        prioritySupport: false,
      },
      featureList: ["8 vidéos par mois (2/semaine)", "Scripts IA personnalisés", "1 langue incluse", "Support standard"],
    },
    {
      id: "silver",
      name: "SILVER",
      subtitle: "Autorité",
      price: 500000,
      currency: "FCFA/mois",
      popular: true,
      features: {
        videos: "12 vidéos (3/semaine)",
        scripts: true,
        languages: "2 langues",
        comments: true,
        multiplatform: false,
        ghostwriting: false,
        accountManager: false,
        monthlyReport: true,
        whatsappVIP: true,
        prioritySupport: false,
      },
      featureList: ["12 vidéos par mois (3/semaine)", "Scripts IA personnalisés", "2 langues incluses", "Réponses commentaires IA", "Rapport mensuel", "Accès groupe WhatsApp VIP"],
    },
    {
      id: "gold",
      name: "GOLD",
      subtitle: "Empire",
      price: 800000,
      promoPrice: 700000,
      currency: "FCFA/mois",
      features: {
        videos: "20 vidéos quotidiennes",
        scripts: true,
        languages: "Langues illimitées",
        comments: true,
        multiplatform: true,
        ghostwriting: true,
        accountManager: true,
        monthlyReport: true,
        whatsappVIP: true,
        prioritySupport: true,
      },
      featureList: ["20 vidéos quotidiennes", "Multi-plateforme", "Ghostwriting VIP", "Langues illimitées", "Account Manager dédié", "Rapport mensuel détaillé", "Accès groupe WhatsApp VIP", "Support prioritaire 24/7"],
    },
  ],
};

export const CASE_STUDIES = [
  {
    id: "1",
    title: "CEO Tech — Présence Multilingue",
    client: "Dirigeant d'une entreprise technologique",
    sector: "Entreprise",
    service: "Ambassadeur Immortel",
    challenge: "Manque de temps pour créer du contenu régulier sur les réseaux sociaux tout en gérant une entreprise en pleine croissance.",
    solution: "Création d'un avatar IA complet avec stratégie de diffusion multilingue sur LinkedIn, YouTube et Instagram.",
    results: { engagement: "+340%", leads: "+150 contacts qualifiés/mois", time: "20h économisées/semaine" },
    testimonial: "ABS Corporation a transformé ma présence en ligne. Mon avatar produit du contenu dans 3 langues pendant que je me concentre sur la croissance de mon entreprise.",
    image: "https://images.unsplash.com/photo-1551434678-e076c223a692?w=800&h=600&fit=crop",
  },
  {
    id: "2",
    title: "Coach Business — Personal Branding",
    client: "Coach business et conférencier international",
    sector: "Coach/Consultant",
    service: "Avatar System",
    challenge: "Besoin de scaler ses formations en ligne sans perdre le contact humain et l'authenticité de sa voix.",
    solution: "Déploiement de l'Avatar System™ avec clonage vocal pour la production automatisée de modules de formation.",
    results: { engagement: "+200%", leads: "+80 inscriptions/mois", time: "15h économisées/semaine" },
    testimonial: "Mon avatar forme mes clients pendant que je dors. C'est la définition même de l'ubiquité numérique.",
    image: "https://images.unsplash.com/photo-1475721027785-f74eccf877e2?w=800&h=600&fit=crop",
  },
  {
    id: "3",
    title: "Institution Gouvernementale — Communication Officielle",
    client: "Ministère de la Communication",
    sector: "Institution",
    service: "Branding 360°",
    challenge: "Moderniser la communication institutionnelle et toucher la jeunesse via les canaux numériques.",
    solution: "Refonte complète de l'identité numérique avec avatars IA pour les communications officielles multilingues.",
    results: { engagement: "+500%", leads: "+2M de vues", time: "30h économisées/semaine" },
    testimonial: "ABS Corporation a révolutionné notre approche de la communication publique. Les résultats parlent d'eux-mêmes.",
    image: "https://images.unsplash.com/photo-1577962917302-cd874c4e31d2?w=800&h=600&fit=crop",
  },
];

export const BLOG_POSTS = [
  {
    id: "1",
    slug: "digital-human-branding-revolution-afrique",
    title: "Le Digital Human Branding : La Révolution Africaine",
    excerpt: "Comment l'intelligence artificielle transforme le personal branding des leaders africains et pourquoi cette révolution ne fait que commencer.",
    category: "Digital Human Branding",
    date: "2025-02-15",
    readTime: "8 min",
    image: "https://images.unsplash.com/photo-1677442136019-21780ecad995?w=800&h=500&fit=crop",
  },
  {
    id: "2",
    slug: "prompt-engineering-guide-complet",
    title: "Prompt Engineering : Le Guide Complet pour les Professionnels",
    excerpt: "Maîtrisez l'art du prompt engineering pour exploiter pleinement le potentiel de l'IA dans votre stratégie de contenu et de branding.",
    category: "Prompt Engineering",
    date: "2025-02-10",
    readTime: "12 min",
    image: "https://images.unsplash.com/photo-1555949963-aa79dcee981c?w=800&h=500&fit=crop",
  },
  {
    id: "3",
    slug: "avatar-ia-ethique-transparence",
    title: "Avatars IA : Éthique et Transparence au Cœur de l'Innovation",
    excerpt: "Notre vision de l'éthique dans la création d'avatars IA et pourquoi la transparence est non-négociable pour ABS Corporation.",
    category: "Éthique IA",
    date: "2025-02-05",
    readTime: "6 min",
    image: "https://images.unsplash.com/photo-1620712943543-bcc4688e7485?w=800&h=500&fit=crop",
  },
  {
    id: "4",
    slug: "roi-personal-branding-ia",
    title: "Mesurer le ROI de votre Personal Branding Augmenté par l'IA",
    excerpt: "Découvrez les métriques clés et les résultats concrets obtenus par nos clients après l'adoption du Digital Human Branding.",
    category: "IA & Leadership",
    date: "2025-01-28",
    readTime: "10 min",
    image: "https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=800&h=500&fit=crop",
  },
  {
    id: "5",
    slug: "clonage-vocal-langues-africaines",
    title: "Clonage Vocal et Langues Africaines : Une Prouesse Technologique",
    excerpt: "Comment ABS Corporation rend le clonage vocal accessible dans les langues locales africaines, préservant l'authenticité et la diversité linguistique.",
    category: "Digital Human Branding",
    date: "2025-01-20",
    readTime: "7 min",
    image: "https://images.unsplash.com/photo-1478737270239-2f02b77fc618?w=800&h=500&fit=crop",
  },
];

export const ACADEMY_PROGRAMS = [
  {
    title: "Prompt Engineering Avancé",
    description: "Maîtriser la rédaction de prompts pour la création de contenu IA. De la structuration des instructions à l'optimisation des résultats, devenez un expert en communication avec l'IA.",
    duration: "4 semaines",
    format: "Présentiel & Distanciel",
    modules: ["Fondamentaux du Prompt Engineering", "Techniques avancées de structuration", "Prompts pour le contenu marketing", "Optimisation et itération", "Projet pratique final"],
    icon: "Terminal",
  },
  {
    title: "Branding IA pour Leaders",
    description: "Construire son image de marque augmentée par l'IA. Apprenez à définir votre positionnement, créer votre identité visuelle et déployer votre présence numérique avec l'aide de l'intelligence artificielle.",
    duration: "6 semaines",
    format: "Présentiel & Hybrid",
    modules: ["Audit de marque personnelle", "Stratégie de positionnement IA", "Création d'identité visuelle", "Contenu automatisé", "Déploiement multi-plateforme"],
    icon: "Award",
  },
  {
    title: "Maîtrise des Outils IA",
    description: "Ateliers pratiques sur HeyGen, ElevenLabs, Midjourney et les outils de pointe. Formation hands-on pour maîtriser les technologies qui façonnent l'avenir du branding.",
    duration: "3 semaines",
    format: "Présentiel",
    modules: ["HeyGen — Avatars vidéo IA", "ElevenLabs — Clonage vocal", "Midjourney — Génération d'images", "Outils complémentaires", "Workflow de production intégré"],
    icon: "Wrench",
  },
  {
    title: "Formation Équipes Marketing",
    description: "Programme sur-mesure pour entreprises. Formez vos équipes marketing et communication aux techniques de l'IA pour le branding, la création de contenu et l'automatisation.",
    duration: "Sur-mesure",
    format: "Sur-mesure entreprise",
    modules: ["Diagnostic des besoins", "Formation aux outils IA", "Intégration workflow existant", "Stratégie de contenu IA", "Suivi post-formation"],
    icon: "Users",
  },
];
